// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function Rules():Promise<Array<core.Rule>>;

export function Scan(arg1:string):Promise<core.Result>;
