// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteCleanup(arg1) {
  return window['go']['main']['App']['ExecuteCleanup'](arg1);
}

export function PreviewCleanup(arg1) {
  return window['go']['main']['App']['PreviewCleanup'](arg1);
}

export function Rules() {
  return window['go']['main']['App']['Rules']();
}

export function Scan(arg1) {
  return window['go']['main']['App']['Scan'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
