// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function Analyze(arg1:string):Promise<core.Analysis>;

export function CachedAnalysis(arg1:string):Promise<core.Analysis>;

export function CancelFolderMap(arg1:string):Promise<void>;

export function ChooseScanRoot():Promise<string>;

export function ExecuteCleanup(arg1:core.CleanupRequest):Promise<core.CleanupResult>;

export function FolderMap(arg1:string):Promise<core.FolderMap>;

export function MeasureFolderMap(arg1:string,arg2:string):Promise<core.FolderMap>;

export function PreviewCleanup(arg1:core.CleanupRequest):Promise<core.CleanupPreview>;

export function RefreshFolderMap(arg1:string,arg2:string):Promise<core.FolderMap>;

export function ReloadFolderMap(arg1:string):Promise<core.FolderMap>;

export function RevealPath(arg1:string):Promise<void>;

export function Rules():Promise<Array<core.Rule>>;

export function Scan(arg1:string):Promise<core.Result>;

export function ScanRoot():Promise<string>;

export function ScanStorage():Promise<core.Storage>;

export function StorageInfo():Promise<core.Storage>;
