// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Rules() {
  return window['go']['main']['App']['Rules']();
}

export function Scan(arg1) {
  return window['go']['main']['App']['Scan'](arg1);
}
