// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function ExecuteCleanup(arg1:core.CleanupRequest):Promise<core.CleanupResult>;

export function PreviewCleanup(arg1:core.CleanupRequest):Promise<core.CleanupPreview>;

export function RevealPath(arg1:string):Promise<void>;

export function Rules():Promise<Array<core.Rule>>;

export function Scan(arg1:string):Promise<core.Result>;

export function ScanStorage():Promise<core.Storage>;

export function StorageInfo():Promise<core.Storage>;
